const demoPages = [
  {id:'persistent-llm-wiki',title:'Persistent LLM Wiki',type:'wiki',date:'2026-07-28',tags:['architecture','llm'],body:'LLM 不只檢索來源，而是持續維護一套可閱讀、可追溯、可累積的 Markdown Wiki。\n\n核心差異：知識只需被編譯一次，之後持續更新，而不是每次提問都重新拼接。',links:['Raw Sources','Wiki Schema','Incremental Ingest','Index and Log','Obsidian as IDE']},
  {id:'raw-sources',title:'Raw Sources',type:'source',date:'2026-07-27',tags:['source-of-truth'],body:'不可變的原始資料層：論文、文章、會議逐字稿、圖片、資料檔。Agent 可以讀取，但不應覆寫。',links:['Persistent LLM Wiki','Incremental Ingest','Citation Provenance']},
  {id:'wiki-schema',title:'Wiki Schema',type:'wiki',date:'2026-07-27',tags:['agents','governance'],body:'AGENTS.md 定義頁面格式、frontmatter、引用方式、檔名規則，以及 ingest / query / lint 的操作守則。',links:['Persistent LLM Wiki','Incremental Ingest','Wiki Lint','Obsidian as IDE']},
  {id:'incremental-ingest',title:'Incremental Ingest',type:'wiki',date:'2026-07-26',tags:['workflow'],body:'每加入一個來源，Agent 會更新摘要、人物、概念、比較、索引與 log。一份來源可能觸及 10–15 個頁面。',links:['Raw Sources','Wiki Schema','Index and Log','Contradiction Detection']},
  {id:'index-log',title:'Index and Log',type:'wiki',date:'2026-07-25',tags:['navigation'],body:'index.md 是內容地圖；log.md 是 append-only 的時間線。兩者讓人與 Agent 都能快速理解 Wiki 的現況。',links:['Persistent LLM Wiki','Incremental Ingest','Hybrid Search']},
  {id:'obsidian-ide',title:'Obsidian as IDE',type:'wiki',date:'2026-07-25',tags:['obsidian'],body:'Obsidian 是知識 IDE：人負責瀏覽、校正與探索；LLM Agent 負責寫入、重構與維護。',links:['Persistent LLM Wiki','Wiki Schema','Graph View','Git Versioning']},
  {id:'hybrid-search',title:'Hybrid Search',type:'wiki',date:'2026-07-24',tags:['search'],body:'小規模先讀 index.md；規模放大後再加入 BM25、vector search 與 reranking。搜尋基礎設施是可選模組，不是起點。',links:['Index and Log','qmd Local Search','Query to Artifact']},
  {id:'graph-view',title:'Graph View',type:'wiki',date:'2026-07-24',tags:['visualization'],body:'圖譜不是目的，而是用來看 hub、孤兒頁面、主題群聚與跨領域連結。',links:['Obsidian as IDE','Wiki Lint','Persistent LLM Wiki']},
  {id:'contradiction-detection',title:'Contradiction Detection',type:'contradiction',date:'2026-07-23',tags:['quality'],body:'新來源與舊結論不一致時，不直接覆蓋。保留兩個主張、來源與時間，建立待裁決項目。',links:['Incremental Ingest','Wiki Lint','Citation Provenance']},
  {id:'wiki-lint',title:'Wiki Lint',type:'wiki',date:'2026-07-23',tags:['quality'],body:'定期檢查矛盾、孤兒頁、過時聲明、缺少頁面的重要概念、引用缺口與可新增的研究問題。',links:['Graph View','Contradiction Detection','Wiki Schema']},
  {id:'query-artifact',title:'Query to Artifact',type:'question',date:'2026-07-22',tags:['compounding'],body:'高價值問答不應留在聊天紀錄。Agent 應能將比較、分析、圖表或決策整理成新 Wiki 頁面，讓探索成果持續累積。',links:['Hybrid Search','Persistent LLM Wiki','Citation Provenance']},
  {id:'citation-provenance',title:'Citation Provenance',type:'wiki',date:'2026-07-21',tags:['trust'],body:'每個重要聲明都能回到原始來源、摘錄位置、擷取日期與 Agent 變更紀錄。',links:['Raw Sources','Contradiction Detection','Query to Artifact']},
  {id:'qmd',title:'qmd Local Search',type:'source',date:'2026-07-20',tags:['tooling'],body:'可選的本地 Markdown 搜尋層，提供 BM25、向量搜尋與 LLM reranking，並可透過 CLI 或 MCP 使用。',links:['Hybrid Search']},
  {id:'git',title:'Git Versioning',type:'wiki',date:'2026-07-19',tags:['versioning'],body:'Wiki 本質上是 Markdown codebase，因此可以用 Git 取得版本歷史、分支、review 與協作。',links:['Obsidian as IDE','Wiki Schema']},
  {id:'agent-question',title:'What changed my thesis?',type:'question',date:'2026-07-18',tags:['reflection'],body:'每次 ingest 後，Agent 應回答：哪些既有結論被強化、削弱或推翻？還缺少什麼證據？',links:['Contradiction Detection','Incremental Ingest','Query to Artifact']}
];

const state={pages:[],filtered:[],selected:null,layer:'all',view:'galaxy',vaultHandle:null,handles:new Map(),camera:{x:0,y:0,scale:1},drag:null,hover:null};
const typeColors={wiki:'#43ddff',source:'#a872ff',question:'#ffca6a',contradiction:'#ff6f91'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];

function slugify(s){return s.toLowerCase().trim().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'')||`page-${Date.now()}`}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function wikiLinks(text){return [...text.matchAll(/\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]/g)].map(m=>m[1].trim())}
function stripFrontmatter(text){return text.replace(/^---\n[\s\S]*?\n---\n?/,'').trim()}
function parseFrontmatter(text){const m=text.match(/^---\n([\s\S]*?)\n---/); const out={}; if(!m)return out; m[1].split('\n').forEach(line=>{const i=line.indexOf(':');if(i>0){let v=line.slice(i+1).trim();if(v.startsWith('['))v=v.slice(1,-1).split(',').map(x=>x.trim().replace(/^['"]|['"]$/g,''));out[line.slice(0,i).trim()]=v}});return out}

function initialize(){state.pages=demoPages.map((p,i)=>({...p,x:0,y:0,vx:0,vy:0,r:p.type==='wiki'?4.4:3.7})); buildGraph(); bind(); updateUI(); requestAnimationFrame(draw)}
function buildGraph(){
  const cx=0,cy=0;state.pages.forEach((p,i)=>{const a=i*2.39996;const rad=38+Math.sqrt(i)*38;p.x=cx+Math.cos(a)*rad+(Math.random()-.5)*18;p.y=cy+Math.sin(a)*rad+(Math.random()-.5)*18;p.vx=p.vy=0});
  const map=new Map(state.pages.map(p=>[p.title.toLowerCase(),p]));
  state.edges=[];state.pages.forEach(p=>(p.links||[]).forEach(t=>{const target=map.get(t.toLowerCase());if(target&&p.id<target.id)state.edges.push({a:p,b:target})}));
  simulate(120);
}
function simulate(iter=40){
  for(let k=0;k<iter;k++){
    for(let i=0;i<state.pages.length;i++)for(let j=i+1;j<state.pages.length;j++){const a=state.pages[i],b=state.pages[j];let dx=b.x-a.x,dy=b.y-a.y,d2=dx*dx+dy*dy+.1,d=Math.sqrt(d2),f=650/d2;dx/=d;dy/=d;a.vx-=dx*f;a.vy-=dy*f;b.vx+=dx*f;b.vy+=dy*f}
    state.edges.forEach(e=>{let dx=e.b.x-e.a.x,dy=e.b.y-e.a.y,d=Math.sqrt(dx*dx+dy*dy)||1,f=(d-74)*.012;e.a.vx+=dx/d*f;e.a.vy+=dy/d*f;e.b.vx-=dx/d*f;e.b.vy-=dy/d*f});
    state.pages.forEach(p=>{p.vx+=-p.x*.0008;p.vy+=-p.y*.0008;p.vx*=.78;p.vy*=.78;p.x+=p.vx;p.y+=p.vy});
  }
}
function updateUI(){
  const q=$('#searchInput').value.trim().toLowerCase();state.filtered=state.pages.filter(p=>(state.layer==='all'||p.type===state.layer)&&(!q||[p.title,p.body,...(p.tags||[])].join(' ').toLowerCase().includes(q)));
  const visible=new Set(state.filtered);state.pages.forEach(p=>p.hidden=!visible.has(p));
  ['all','wiki','source','question','contradiction'].forEach(t=>$('#count'+t[0].toUpperCase()+t.slice(1)).textContent=t==='all'?state.pages.length:state.pages.filter(p=>p.type===t).length);
  $('#metricPages').textContent=state.pages.filter(p=>p.type==='wiki').length;$('#metricLinks').textContent=state.edges.length;
  const degrees=new Map(state.pages.map(p=>[p.id,0]));state.edges.forEach(e=>{degrees.set(e.a.id,degrees.get(e.a.id)+1);degrees.set(e.b.id,degrees.get(e.b.id)+1)});
  $('#metricOrphans').textContent=[...degrees.values()].filter(v=>v===0).length;$('#metricContradictions').textContent=state.pages.filter(p=>p.type==='contradiction').length;
  renderActivity();renderTimeline();renderLint(degrees);
}
function renderActivity(){const list=[...state.pages].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,7);$('#activityList').innerHTML=list.map(p=>`<div class="activity-item"><i style="color:${typeColors[p.type]};background:${typeColors[p.type]}"></i><div><strong>${escapeHtml(p.title)}</strong><small>${p.date} · ${p.type}</small></div></div>`).join('')}
function renderTimeline(){const list=[...state.pages].sort((a,b)=>b.date.localeCompare(a.date));$('#timelineList').innerHTML=list.map(p=>`<div class="timeline-item"><time>${p.date}</time><div class="timeline-line"></div><div><strong>${escapeHtml(p.title)}</strong><p>${escapeHtml(p.body.slice(0,90))}${p.body.length>90?'…':''}</p></div></div>`).join('')}
function renderLint(degrees){const orphan=[...degrees].filter(([,v])=>v===0).map(([id])=>state.pages.find(p=>p.id===id)?.title).filter(Boolean);const missing=[];const titles=new Set(state.pages.map(p=>p.title.toLowerCase()));state.pages.forEach(p=>(p.links||[]).forEach(l=>{if(!titles.has(l.toLowerCase()))missing.push(l)}));const rows=[['孤立頁面',orphan.length?orphan.join('、'):'無'],['缺少目標頁面的連結',[...new Set(missing)].slice(0,6).join('、')||'無'],['待裁決矛盾',state.pages.filter(p=>p.type==='contradiction').map(p=>p.title).join('、')||'無'],['缺少來源標記',`${state.pages.filter(p=>p.type==='wiki'&&!p.source).length} 個 Wiki 頁面尚未綁定 source`]];$('#lintResults').innerHTML=rows.map(r=>`<div class="lint-row"><span>${r[0]}</span><b>${escapeHtml(r[1])}</b></div>`).join('')}

const canvas=$('#galaxyCanvas'),ctx=canvas.getContext('2d');let dpr=1;
function resize(){dpr=Math.min(devicePixelRatio||1,2);const r=canvas.getBoundingClientRect();canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
function worldToScreen(p){const r=canvas.getBoundingClientRect();return{x:r.width/2+(p.x+state.camera.x)*state.camera.scale,y:r.height/2+(p.y+state.camera.y)*state.camera.scale}}
function screenToWorld(x,y){const r=canvas.getBoundingClientRect();return{x:(x-r.width/2)/state.camera.scale-state.camera.x,y:(y-r.height/2)/state.camera.scale-state.camera.y}}
function drawStars(w,h){ctx.save();for(let i=0;i<180;i++){const x=(i*83.17)%w,y=(i*47.33)%h,a=.08+((i*19)%30)/100;ctx.fillStyle=`rgba(125,205,255,${a})`;ctx.fillRect(x,y,i%13===0?1.4:.7,i%13===0?1.4:.7)}ctx.restore()}
function draw(){resize();const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);drawStars(r.width,r.height);
  ctx.save();ctx.globalCompositeOperation='lighter';state.edges.forEach(e=>{if(e.a.hidden||e.b.hidden)return;const a=worldToScreen(e.a),b=worldToScreen(e.b);const active=state.selected&&(e.a===state.selected||e.b===state.selected);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=active?'rgba(82,229,255,.58)':'rgba(47,143,191,.13)';ctx.lineWidth=active?1.15:.55;ctx.stroke()});
  state.pages.forEach(p=>{if(p.hidden)return;const s=worldToScreen(p),selected=p===state.selected,hover=p===state.hover;const rr=(p.r+(selected?3:hover?1.5:0))*Math.min(state.camera.scale,1.7);const grd=ctx.createRadialGradient(s.x,s.y,0,s.x,s.y,rr*5);grd.addColorStop(0,typeColors[p.type]+'cc');grd.addColorStop(.18,typeColors[p.type]+'66');grd.addColorStop(1,typeColors[p.type]+'00');ctx.fillStyle=grd;ctx.beginPath();ctx.arc(s.x,s.y,rr*5,0,Math.PI*2);ctx.fill();ctx.fillStyle=typeColors[p.type];ctx.beginPath();ctx.arc(s.x,s.y,Math.max(1.7,rr),0,Math.PI*2);ctx.fill();if(selected||hover||state.camera.scale>1.6){ctx.globalCompositeOperation='source-over';ctx.fillStyle=selected?'#f3fdff':'#9ec8d8';ctx.font=`${selected?12:10}px system-ui`;ctx.fillText(p.title,s.x+rr+5,s.y+3);ctx.globalCompositeOperation='lighter'}});ctx.restore();requestAnimationFrame(draw)}
function hitTest(x,y){let best=null,bd=14;state.filtered.forEach(p=>{const s=worldToScreen(p),d=Math.hypot(s.x-x,s.y-y);if(d<bd){best=p;bd=d}});return best}

function selectPage(p){state.selected=p;$('#inspectorEmpty').classList.add('hidden');$('#inspector').classList.remove('hidden');$('.right-sidebar').classList.add('open');$('#nodeType').textContent=p.type;$('#nodeTitle').textContent=p.title;$('#nodeMeta').textContent=`${p.date||'—'} · ${(p.tags||[]).map(t=>'#'+t).join(' ')}`;$('#nodeBody').textContent=p.body;$('#nodeLinks').innerHTML=(p.links||[]).map(l=>`<button class="chip" data-title="${escapeHtml(l)}">[[${escapeHtml(l)}]]</button>`).join('')||'<span class="chip">No links</span>';$$('#nodeLinks .chip[data-title]').forEach(b=>b.onclick=()=>{const target=state.pages.find(p=>p.title===b.dataset.title);if(target)selectPage(target)});}

async function connectVault(){
  if(!window.showDirectoryPicker){toast('此瀏覽器不支援資料夾讀寫；建議用桌面版 Chrome / Edge');return}
  try{const handle=await window.showDirectoryPicker({mode:'readwrite'});state.vaultHandle=handle;state.handles.clear();const pages=[];await walk(handle,'',pages);if(!pages.length){toast('Vault 中沒有找到 Markdown 檔');return}state.pages=pages;$('#vaultStatus').textContent=handle.name;$('#vaultStatus').style.color='var(--cyan)';buildGraph();updateUI();toast(`已連接 ${handle.name}，載入 ${pages.length} 個頁面`)}catch(e){if(e.name!=='AbortError'){console.error(e);toast('連接失敗：'+e.message)}}
}
async function walk(dir,path,out){for await(const [name,h] of dir.entries()){if(name.startsWith('.')||name==='.obsidian')continue;const p=path?`${path}/${name}`:name;if(h.kind==='directory')await walk(h,p,out);else if(name.toLowerCase().endsWith('.md')){const file=await h.getFile(),text=await file.text(),fm=parseFrontmatter(text),title=(fm.title||name.replace(/\.md$/i,''));const type=['wiki','source','question','contradiction'].includes(fm.type)?fm.type:(p.startsWith('raw/')?'source':'wiki');const page={id:slugify(p),title,type,date:fm.updated||fm.date||new Date(file.lastModified).toISOString().slice(0,10),tags:Array.isArray(fm.tags)?fm.tags:[],body:stripFrontmatter(text).slice(0,5000),links:wikiLinks(text),path:p,handle:h,x:0,y:0,vx:0,vy:0,r:type==='wiki'?4.4:3.7};out.push(page);state.handles.set(page.id,h)}}}
async function createPage(){const title=$('#pageTitleInput').value.trim(),type=$('#pageTypeInput').value,body=$('#pageBodyInput').value.trim();if(!title)return;const page={id:slugify(title+'-'+Date.now()),title,type,date:new Date().toISOString().slice(0,10),tags:[],body,links:wikiLinks(body),x:(Math.random()-.5)*160,y:(Math.random()-.5)*160,vx:0,vy:0,r:type==='wiki'?4.4:3.7};if(state.vaultHandle){try{let wikiDir;try{wikiDir=await state.vaultHandle.getDirectoryHandle(type==='source'?'raw':'wiki',{create:true})}catch{wikiDir=state.vaultHandle}const h=await wikiDir.getFileHandle(`${title.replace(/[\\/:*?"<>|]/g,'-')}.md`,{create:true});const w=await h.createWritable();const md=`---\ntitle: "${title.replace(/"/g,'\\"')}"\ntype: ${type}\ndate: ${page.date}\ntags: []\n---\n\n# ${title}\n\n${body}\n`;await w.write(md);await w.close();page.handle=h;page.path=`${type==='source'?'raw':'wiki'}/${title}.md`;toast('已寫入 Obsidian Vault')}catch(e){console.error(e);toast('寫入 Vault 失敗，已先加入目前工作階段')}}state.pages.push(page);buildGraph();updateUI();selectPage(page);$('#pageDialog').close();$('#pageForm').reset()}
function openObsidian(){if(!state.selected)return;const vault=state.vaultHandle?.name||'';const file=(state.selected.path||state.selected.title).replace(/\.md$/,'');const uri=`obsidian://open?vault=${encodeURIComponent(vault)}&file=${encodeURIComponent(file)}`;location.href=uri}
function runLint(){switchView('health');toast('Lint 完成：已檢查孤兒頁、斷鏈、矛盾與引用缺口')}
function switchView(v){state.view=v;$$('.view-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view-container').forEach(el=>el.classList.remove('active'));$('#'+v+'View').classList.add('active')}
function askAgent(){const q=$('#agentPrompt').value.trim();if(!q)return;const save=$('#saveAnswerToggle').classList.contains('active');const relevant=state.pages.filter(p=>[p.title,p.body].join(' ').toLowerCase().includes(q.toLowerCase().split(/\s+/)[0])).slice(0,3);const names=(relevant.length?relevant:state.pages.slice(0,3)).map(p=>`[[${p.title}]]`).join('、');const answer=`問題：${q}\n\n目前原型會先從 Wiki 索引與連結圖找候選頁面，再將回答寫成可回存的 Markdown artifact。建議優先閱讀 ${names}，並在正式版串接你的 LLM Agent / MCP 來做引用、差異更新與多檔案寫入。`;if(save){$('#pageTitleInput').value=`Exploration — ${q.slice(0,28)}`;$('#pageTypeInput').value='question';$('#pageBodyInput').value=answer;$('#pageDialog').showModal()}else toast('已完成本地端示範推理（正式版需接 LLM API）')}

function bind(){
  addEventListener('resize',resize);$('#connectVault').onclick=connectVault;$('#newPage').onclick=()=>$('#pageDialog').showModal();$('#createPageSubmit').onclick=e=>{e.preventDefault();createPage()};$('#searchInput').oninput=updateUI;$('#searchInput').onkeydown=e=>{if(e.key==='Escape'){e.target.value='';updateUI()}};
  $$('.layer').forEach(b=>b.onclick=()=>{state.layer=b.dataset.layer;$$('.layer').forEach(x=>x.classList.toggle('active',x===b));updateUI()});$$('.view-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#runLint').onclick=runLint;$('#closeInspector').onclick=()=>{$('#inspector').classList.add('hidden');$('#inspectorEmpty').classList.remove('hidden');$('.right-sidebar').classList.remove('open');state.selected=null};$('#openInObsidian').onclick=openObsidian;
  $('#resetView').onclick=()=>state.camera={x:0,y:0,scale:1};$('#focusMode').onclick=()=>{if(state.selected){state.camera.x=-state.selected.x;state.camera.y=-state.selected.y;state.camera.scale=2.2}};
  canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);state.drag={x:e.clientX,y:e.clientY,cx:state.camera.x,cy:state.camera.y,moved:false}});canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();state.hover=hitTest(e.clientX-r.left,e.clientY-r.top);canvas.style.cursor=state.hover?'pointer':state.drag?'grabbing':'grab';if(state.drag){const dx=e.clientX-state.drag.x,dy=e.clientY-state.drag.y;if(Math.abs(dx)+Math.abs(dy)>3)state.drag.moved=true;state.camera.x=state.drag.cx+dx/state.camera.scale;state.camera.y=state.drag.cy+dy/state.camera.scale}});canvas.addEventListener('pointerup',e=>{if(state.drag&&!state.drag.moved){const r=canvas.getBoundingClientRect(),p=hitTest(e.clientX-r.left,e.clientY-r.top);if(p)selectPage(p)}state.drag=null});canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.scale=Math.max(.35,Math.min(4,state.camera.scale*Math.exp(-e.deltaY*.001)))},{passive:false});
  $('#openCommand').onclick=()=>{$('#commandDialog').showModal();setTimeout(()=>$('#commandInput').focus(),20)};addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#commandDialog').showModal()}if(e.key==='/'&&document.activeElement.tagName!=='INPUT'&&document.activeElement.tagName!=='TEXTAREA'){e.preventDefault();$('#searchInput').focus()}});$$('[data-command]').forEach(b=>b.onclick=()=>{const c=b.dataset.command;$('#commandDialog').close();if(c==='connect')connectVault();if(c==='new')$('#pageDialog').showModal();if(c==='lint')runLint();if(c==='reset')state.camera={x:0,y:0,scale:1}});
  $('#saveAnswerToggle').onclick=e=>e.currentTarget.classList.toggle('active');$('#askAgent').onclick=askAgent;$$('[data-agent]').forEach(b=>b.onclick=()=>{if(!state.selected)return;const prompts={synthesize:`綜合 [[${state.selected.title}]] 與所有相鄰頁面，形成一份可長期維護的 synthesis。`,expand:`檢查 [[${state.selected.title}]] 的證據缺口、孤立概念與下一個研究問題。`,cite:`根據 [[${state.selected.title}]] 的 raw sources 產生逐項可追溯摘要。`};$('#agentPrompt').value=prompts[b.dataset.agent];askAgent()});
}
initialize();
